### ISSUE TITLE
Tracker files with additional .NT file, any thoughts as to it's purpose?

### ISSUE THREAD

**Issue by NebularNerd** [cmatsuoka/tracker-history#6]
I've been clearing through my hoard of old files and came across three songs that have both a mod and then a secondary .NT file. For the life of me I cannot see what/if any purpose they serve. The mod's have the standard `M.K.` at offset 1080 and can in the case of `mod.startreksymphony` I can find an exact CRC32 at [Mod Archive](https://modarchive.org/index.php?request=search&query=startreksymphony&submit=Find&search_type=filename_or_songtitle).

I would be interested in any info on what purpose these may serve. They all have a file header of `0x53 54 31 2E 33 20 4D 6F 64 75 6C 65 49 4E 46 4F` / `ST1.3 ModuleINFO`

[Mods with NT file.zip](https://github.com/cmatsuoka/tracker-history/files/14459822/Mods.with.NT.file.zip)

**EDIT:**
-A little more info, it's classed by TrID as a [Startrekker 1.x module info](https://file-extension.net/seeker/program_extension_startrekker) with a much shorter header match (They skip the subversion).
- Loading a standard .mod into StarTracker 1.3/1.2 then saving it back out creates the `.NT` file. This means it's some sort of secondary info with `ST1.3`/`ST1.2` in the header

**Comment by stefandrissen** [comment]
based on [OpenMPT](https://github.com/OpenMPT/openmpt/blob/4f9473ac66e752e39115f2aadc52502a7e4b90e5/soundlib/Load_mod.cpp#L1281) I would guess that those comments apply:

> Detect Startrekker files with external synth instruments.

And once you know what to google for, you can find stuff about [StarTrekker](https://nostalgicplayer.dk/modules/format/startrekker/2):

>This is a NoiseTracker clone, but improved by the possibility to have synth samples, which are stored in an external file with the extension .nt. NostalgicPlayer supports playing synth sound, if the file is found.

**Comment by NebularNerd** [comment]
Ahhhhh...... This all makes sense, the Zelda track sounds terrible outside of StarTrekker, this explains why. Thanks 🙂👏

I shall now ensure I keep the .NT files with the mods. 

@cmatsuoka I wonder if this might be a suitable addition to your StarTrekker data?
